/*
 * This the MOINMOIN license
 * you can do that you want !!!!!!!!!
 */

/*
 * AudioConfigurationPanel.java
 *
 * Created on 9 mai 2009, 14:24:55
 */

package SoftPhone.UI.Configuration;

import SoftPhone.Configuration.Media.MediaConfigurationLoader;
import SoftPhone.Configuration.Sound.AudioConfiguration;
import SoftPhone.Configuration.Sound.AudioConfigurationLoader;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;
import javax.swing.event.ListDataListener;

/**
 *
 * @author didier
 */
public class AudioConfigurationPanel extends javax.swing.JPanel {

    private AudioConfigurationLoader soundConfigurationLoader;
    private MediaConfigurationLoader mediaConfigurationLoader;
    private String[] soundDevicesNames;
    private JFrame frame;
    private AudioConfiguration soundConfiguration;


    /** Creates new form AudioConfigurationPanel */

     public AudioConfigurationPanel(JFrame parent,AudioConfigurationLoader scl,MediaConfigurationLoader mcl)
     {
       this.frame =parent;
       this.soundConfigurationLoader =scl;
       this.mediaConfigurationLoader=mcl;
       this.soundConfiguration=
                    soundConfigurationLoader.getSoundConfigurationInstance();
        soundDevicesNames =soundConfigurationLoader.getSoundDevicesNames();
        initComponents();
        for(String device:soundDevicesNames)
        {
            audioDeviceComboBox.addItem(device);
            
        }
        if(soundConfigurationLoader.isConfigured())
        {
            audioDeviceComboBox
                 .setSelectedItem(soundConfiguration.getPreferredSoundDevice());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        audioDeviceComboBox = new javax.swing.JComboBox();
        audioDeviceLabel = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        audioDeviceLabel.setText("Périphérique  audio");

        OkButton.setText("Valider");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Selectionnez un périphérique audio dans la liste ci-dessous");

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addGap(138, 138, 138)
                        .addComponent(OkButton))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(audioDeviceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(audioDeviceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(audioDeviceLabel)
                    .addComponent(audioDeviceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
       String device =(String)audioDeviceComboBox.getSelectedItem();
       System.out.println(device);
        soundConfigurationLoader.setPreferredSoundDevice(device);
        soundConfigurationLoader.setConfigured(true);
        soundConfigurationLoader.save();
        this.frame.dispose();
        
    }//GEN-LAST:event_OkButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
this.frame.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkButton;
    private javax.swing.JComboBox audioDeviceComboBox;
    private javax.swing.JLabel audioDeviceLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
