/*
 * GeneralConfigurationPanel.java
 *
 * Created on 16 juin 2009, 23:44
 */

package SoftPhone.UI.Configuration;

import SoftPhone.Configuration.GeneralConfigurationLoader;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author  Administrateur
 */
public class GeneralConfigurationPanel extends javax.swing.JPanel {
    private GeneralConfigurationLoader generalConfigurationLoader;
    private JFrame frame;
    

    /** Creates new form GeneralConfigurationPanel */
    public GeneralConfigurationPanel(JFrame frame,GeneralConfigurationLoader gConfLoader) 
    {
        this.generalConfigurationLoader=gConfLoader;
        this.frame =frame;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pathLabel = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setText("Répertoire du compte SIP et du carnet de Contact");

        pathLabel.setText(generalConfigurationLoader.getConfiguration().getPrefferedPath() );

        selectButton.setText("Changer");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancelButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectButton))
                        .addComponent(jLabel1)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pathLabel)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectButton)
                    .addComponent(cancelButton))
                .addContainerGap(112, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
      JFileChooser fileChooser =new JFileChooser(
  new File(generalConfigurationLoader.getConfiguration().getPrefferedPath()));
      fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
      int result =fileChooser.showDialog(this, "Selectionner");
      if(result == JFileChooser.APPROVE_OPTION)
      {
          String path =fileChooser.getSelectedFile().getPath();
          generalConfigurationLoader.setPrefferedPath(path);
      }
}//GEN-LAST:event_selectButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
this.frame.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JButton selectButton;
    // End of variables declaration//GEN-END:variables

}
