/*
 * RTPConfigurationPanel.java
 *
 * Created on 17 juin 2009, 00:30
 */

package SoftPhone.UI.Configuration;

import SoftPhone.Configuration.RTP.RTPConfigurationLoader;
import SoftPhone.Network.NetworkUtils;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  Administrateur
 */
public class RTPConfigurationPanel extends javax.swing.JPanel {
    private RTPConfigurationLoader rtpConfigurationLoader;
    private JFrame frame;

    /** Creates new form RTPConfigurationPanel */
    public RTPConfigurationPanel(JFrame frame,RTPConfigurationLoader rtpcl) 
    {
        this.frame=frame;
        this.rtpConfigurationLoader=rtpcl;
        initComponents(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        port1Field = new javax.swing.JTextField();
        port2Field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        jLabel1.setText("Premier port");

        jLabel2.setText("Dernier port");

        String f=Integer.toString(this.rtpConfigurationLoader.getFirstPrefferredRtpPort());
        port1Field.setText(f);

        String l=Integer.toString(this.rtpConfigurationLoader.getLastPrefferredRtpPort());
        port2Field.setText(l);

        jLabel3.setText("Fourchette de ports RTP");

        OkButton.setText("Valider");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(port1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelButton)
                                    .addComponent(port2Field))))
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OkButton)
                        .addGap(70, 70, 70))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(port1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(port2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OkButton)
                    .addComponent(cancelButton))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
    validateRTPPort(this.port1Field.getText() ,this.port2Field.getText());
   this.frame.dispose();
}//GEN-LAST:event_OkButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
this.frame.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OkButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField port1Field;
    private javax.swing.JTextField port2Field;
    // End of variables declaration//GEN-END:variables

    private void validateRTPPort(String firstPort  ,String lastPort )
    {
        try 
        {
            int port1 =Integer.parseInt(firstPort);
            int port2 =Integer.parseInt(lastPort);
            if(NetworkUtils.ValidatePortNumber(port1)
                    &&NetworkUtils.ValidatePortNumber(port2))
        {
            this.rtpConfigurationLoader.setRtpPortRange(port1, port2);
        }
        else
        {
            showBadPortMessage();
        }
        }
        catch(NumberFormatException ex)
        {
            showBadPortMessage();
        }
}
    
    private void showBadPortMessage()
    {
        JOptionPane.showMessageDialog(this
                     , "Saisissez un numéro de port valide. " +
                     "\n la valeur doit être entière et supérieur à  1024"
                     ,"Numéro de port invalide !"
                     ,JOptionPane.WARNING_MESSAGE);
    }
}
