/*
 * This the MOINMOIN license
 * you can do that you want !!!!!!!!!
 */

/*
 * AccountPanel.java
 *
 * Created on 31 mai 2009, 19:15:14
 */

package SoftPhone.UI.Sip;

import SoftPhone.Configuration.Account.AccountLoader;
import SoftPhone.Network.NetworkUtils;
import SoftPhone.Protocol.Sip.Account.SipAccount;
import SoftPhone.Protocol.Sip.Agent.SipProxy;
import SoftPhone.Protocol.Sip.Agent.SipRegistrar;
import SoftPhone.Protocol.Sip.SipUtils;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author didier
 */
public class SipAccountPanel extends javax.swing.JPanel {

    /** Creates new form AccountPanel */
    private JFrame parent;
    private AccountLoader accountLoader;
    private SipAccount account;
    private SipProxy proxy;
    private SipRegistrar registrar;
    public SipAccountPanel(JFrame parent, AccountLoader accountLoader)
    {
        this.parent= parent;
        this.accountLoader =accountLoader;
        initComponents();
         
        if(this.accountLoader.isConfigured())
        {
            account = accountLoader.getConfiguredAccount();
            proxy =account.getProxy();
            registrar =account.getRegistrar();
            this.accountNameField.setText(account.getAccountName());
            this.userNameField.setText(account.getAccountUsername());
            this.passField.setText(account.getAccountUserPassword());
            this.sipAddressField.setText(account.getSipAddress());
            this.proxyAddressField.setText(proxy.getUri());
            this.proxyPortField.setText(Integer.toString(proxy.getPort()));
            this.registrarAddressField.setText(registrar.getSipAddress());
            this.registrarPortField.setText(Integer.toString(registrar.getPort()));
        }
        else
        {
             account = accountLoader.getSipAccount();
            proxy =account.getProxy();
            registrar =account.getRegistrar();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        sipAddressLabel = new javax.swing.JLabel();
        sipAccountLabel = new javax.swing.JLabel();
        proxyLabel = new javax.swing.JLabel();
        proxyAddressLabel = new javax.swing.JLabel();
        proxyPortLabel = new javax.swing.JLabel();
        registrarLabel = new javax.swing.JLabel();
        registrarAddressLabel = new javax.swing.JLabel();
        registrarPortLabel = new javax.swing.JLabel();
        accountNameField = new javax.swing.JTextField();
        userNameField = new javax.swing.JTextField();
        sipAddressField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        proxyAddressField = new javax.swing.JTextField();
        proxyPortField = new javax.swing.JTextField();
        registrarAddressField = new javax.swing.JTextField();
        registrarPortField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        accountLabel.setText("Nom du compte : ");

        userNameLabel.setText("Nom d'utilisateur :");

        passLabel.setText("Mot de passe :");

        sipAddressLabel.setText("Adresse SIP : ");

        sipAccountLabel.setText("Compte SIP");

        proxyLabel.setText("Proxy SIP");

        proxyAddressLabel.setText("Adresse : ");

        proxyPortLabel.setText("Port du Proxy :");

        registrarLabel.setText("Registrar");

        registrarAddressLabel.setText("Adresse : ");

        registrarPortLabel.setText("Port du Registrar : ");

        accountNameField.setMinimumSize(new java.awt.Dimension(12, 30));
        accountNameField.setPreferredSize(new java.awt.Dimension(12, 30));
        accountNameField.setRequestFocusEnabled(false);

        userNameField.setMinimumSize(new java.awt.Dimension(12, 30));
        userNameField.setPreferredSize(new java.awt.Dimension(12, 30));
        userNameField.setRequestFocusEnabled(false);

        sipAddressField.setText("sip:");

        proxyAddressField.setText("sip:");

        proxyPortField.setText("5060");

        registrarAddressField.setText("sip:");

        registrarPortField.setText("5060");

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("Valider");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(registrarLabel)
                .addContainerGap(268, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(registrarPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(sipAddressField, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameLabel)
                    .addComponent(sipAddressLabel)
                    .addComponent(passLabel)
                    .addComponent(accountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(accountNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(sipAccountLabel)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(proxyLabel)
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(proxyPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(passField, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proxyPortLabel)
                            .addComponent(proxyAddressLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarAddressLabel)
                            .addComponent(registrarPortLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(okButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(proxyAddressField, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(registrarAddressField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sipAccountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accountLabel)
                    .addComponent(accountNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sipAddressLabel)
                    .addComponent(sipAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(proxyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(proxyAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(proxyAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proxyPortLabel)
                    .addComponent(proxyPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registrarAddressLabel)
                    .addComponent(registrarAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarPortLabel)
                    .addComponent(registrarPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    this.parent.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    
     account.setAccountName(accountNameField.getText());
     account.setAccountUserName(userNameField.getText());
     validateSipAddress(sipAddressField.getText());
     account.setAccountUserPassword(passField.getText());
     
     
     validateProxyURI(proxyAddressField.getText());
     validateProxyPort(proxyPortField.getText());
     
     validateRegirarSipAddress(registrarAddressField.getText());
     validateRegistrarPort(registrarPortField.getText() );
     accountLoader.save();
     accountLoader.setConfigured(true);
     this.parent.dispose(); 


    }//GEN-LAST:event_okButtonActionPerformed

    private void validateSipAddress(String sipAddress)
    {
         if(SipUtils.validateSipAddress(sipAddress))
         {
           account.setSipAddress(sipAddress);
         }

         else
         {
             showBadSipAddressMessage();
         }

    }

   

    private void validateProxyPort(String proxyPort)
    {
        try
        {
            int port =Integer.parseInt(proxyPort);
        if(NetworkUtils.ValidatePortNumber(port))
        {
            proxy.setPort(proxyPort);
        }
        else
        {
            showBadPortMessage();
        }
        }
        
        catch(NumberFormatException ex)
        {
            showBadPortMessage();
        }
      
        
    }

    private void validateProxyURI(String uri)
    {
         if(SipUtils.validateSipAddress(uri))
         {
           proxy.setUri(uri);
         }

         else
         {
             showBadSipAddressMessage();
         }
         
    }

    private void validateRegirarSipAddress(String sipAddress)
    {
        if(SipUtils.validateRegistrarSipAddress(sipAddress))
        {
            registrar.setSipAddress(sipAddress);
        }

        else
        {
            showInvaliRegistrarMessage();
        }
    }

    private void validateRegistrarPort(String Port)
    {
        try 
        {
            int port =Integer.parseInt(Port);
            if(NetworkUtils.ValidatePortNumber(port))
        {
           registrar.setPort(Port);
        }
        else
        {
            showBadPortMessage();
        }
        }
        catch(NumberFormatException ex)
        {
            showBadPortMessage();
        }
        
    }

    private void showBadSipAddressMessage()
    {
        JOptionPane.showMessageDialog(this
                     , "Saisissez une adresse SIP valide " +
                     "\n de la forme:sip:utilisateur@domain.fr"
                     ,"Adresse SIP invalide !"
                     ,JOptionPane.WARNING_MESSAGE);
    }
    
    private void showInvaliRegistrarMessage()
    {
         JOptionPane.showMessageDialog(this
                     , "Saisissez une adresse de registrar valide " +
                     "\n comme : sip:domain.fr"
                     ,"Adresse registrar invalide !"
                     ,JOptionPane.WARNING_MESSAGE);
        
    }



    private void showBadPortMessage()
    {
        JOptionPane.showMessageDialog(this
                     , "Saisissez un numéro de port valide. " +
                     "\n la valeur doit être entière et supérieur à  1024"
                     ,"Numéro de port invalide !"
                     ,JOptionPane.WARNING_MESSAGE);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JTextField accountNameField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField proxyAddressField;
    private javax.swing.JLabel proxyAddressLabel;
    private javax.swing.JLabel proxyLabel;
    private javax.swing.JTextField proxyPortField;
    private javax.swing.JLabel proxyPortLabel;
    private javax.swing.JTextField registrarAddressField;
    private javax.swing.JLabel registrarAddressLabel;
    private javax.swing.JLabel registrarLabel;
    private javax.swing.JTextField registrarPortField;
    private javax.swing.JLabel registrarPortLabel;
    private javax.swing.JLabel sipAccountLabel;
    private javax.swing.JTextField sipAddressField;
    private javax.swing.JLabel sipAddressLabel;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables

}
